#!/usr/bin/env bash
set -Eeuo pipefail

source_setup_safely() {
    local setup_file="$1"

    if [[ ! -f "$setup_file" ]]; then
        echo "[ERROR] Setup file not found: $setup_file"
        return 1
    fi

    # ROS setup scripts may reference optional variables that are unset.
    # Temporarily disable nounset while sourcing them.
    set +u
    # shellcheck disable=SC1090
    source "$setup_file"
    set -u
}

ROS_SETUP="/opt/ros/${ROS_DISTRO}/setup.bash"

echo "[INFO] Loading ROS2 environment: $ROS_SETUP"
source_setup_safely "$ROS_SETUP"

echo "[INFO] Workspace: $WORKSPACE_DIR"

if [[ ! -d "$WORKSPACE_DIR/src" ]]; then
    echo "[ERROR] Workspace source directory not found:"
    echo "        $WORKSPACE_DIR/src"
    exit 1
fi

cd "$WORKSPACE_DIR"

echo "[INFO] Installing ROS package dependencies with rosdep..."
rosdep install \
    --from-paths src \
    --ignore-src \
    --rosdistro "$ROS_DISTRO" \
    -r \
    -y

echo "[INFO] Removing previous build and log directories..."
rm -rf build log

echo "[INFO] Building Scout Mini workspace..."
colcon build \
    --symlink-install \
    --executor parallel \
    --parallel-workers "$BUILD_JOBS" \
    --event-handlers console_direct+

if [[ ! -f "$WORKSPACE_DIR/install/setup.bash" ]]; then
    echo "[ERROR] Build did not create:"
    echo "        $WORKSPACE_DIR/install/setup.bash"
    exit 1
fi

CONFIG_DIR="$HOME/.config/scout_mini_quickstart"
ROS_ENV_FILE="$CONFIG_DIR/ros_env.sh"

mkdir -p "$CONFIG_DIR"

cat > "$ROS_ENV_FILE" <<EOF_ENV
#!/usr/bin/env bash

# Generated by Scout Mini Quickstart.

export ROS_DOMAIN_ID="${ROS_DOMAIN_ID}"
export ROS_LOCALHOST_ONLY="${ROS_LOCALHOST_ONLY}"
export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION}"

_scout_nounset_enabled=0

case "\$-" in
    *u*)
        _scout_nounset_enabled=1
        set +u
        ;;
esac

source "/opt/ros/${ROS_DISTRO}/setup.bash"
source "${WORKSPACE_DIR}/install/setup.bash"

if [[ "\$_scout_nounset_enabled" -eq 1 ]]; then
    set -u
fi

unset _scout_nounset_enabled
EOF_ENV

chmod +x "$ROS_ENV_FILE"

BASHRC_LINE='[[ -f "$HOME/.config/scout_mini_quickstart/ros_env.sh" ]] && source "$HOME/.config/scout_mini_quickstart/ros_env.sh"'

touch "$HOME/.bashrc"

if ! grep -Fqx "$BASHRC_LINE" "$HOME/.bashrc"; then
    echo "$BASHRC_LINE" >> "$HOME/.bashrc"
    echo "[INFO] Added Scout Mini ROS environment to ~/.bashrc"
else
    echo "[INFO] Scout Mini ROS environment is already registered."
fi

echo "[OK] Workspace built successfully."
echo "[OK] Environment file created: $ROS_ENV_FILE"
EOF
